import type { ServiceLevel } from './types';

export const serviceLevels: ServiceLevel[] = [
  {
    level: 'A',
    title: 'Verhuismedewerker',
    rate: '€ 25,00 – € 27,50 p/u',
    services: [
      'basis sjouw- en logistieke werkzaamheden;',
      'zorgvuldig omgaan met meubels en dozen;',
      'uitvoering binnen afgesproken veiligheidskaders.',
    ],
    requirements: ['eigen PBM en professionele werkkleding;', 'VCA Basis (gewenst).'],
    rangeApplication: [
      'onderkant: eenvoudige, repeterende inzet;',
      'bovenkant: tempo, zorgvuldigheid, zelfstandig uitvoerbaar binnen scope.',
    ],
  },
  {
    level: 'B',
    title: 'Assistent Verhuizer',
    rate: '€ 26,00 – € 30,00 p/u',
    services: [
      'eenvoudige de- en montage van standaardmeubelen (bijv. IKEA-achtige meubels);',
      'correct inpakken van verhuisdozen (niet-breekbare goederen) en labelen;',
      'ondersteuning bij laad- en loswerk;',
      'zorgvuldig omgaan met verpakkingsmateriaal en goederen;',
      'veilig tillen met hulpmiddelen.',
    ],
    requirements: [
      'SAVAM Assistent Verhuizer (gewenst);',
      'VCA Basis;',
      'rijbewijs B (gewenst);',
      'eigen PBM en basisgereedschap.',
    ],
    rangeApplication: ['onderkant: ondersteunend karakter;', 'bovenkant: hoge zelfstandigheid binnen afgebakende taken.'],
  },
  {
    level: 'C',
    title: 'Verhuizer (volwaardig)',
    rate: '€ 29,00 – € 32,00 p/u',
    services: [
      'zelfstandige uitvoering van verhuiswerkzaamheden;',
      'volledige demontage en montage van meubilair;',
      'inpakken van verhuisdozen (breekbare en niet-breekbare goederen) conform EV-/ISO-normen;',
      'zelfstandig laden, stuwen, borgen en schadepreventie van verhuisgoederen in verhuiswagen/bus/container/liftvan;',
      'opmaken van gedetailleerde inventarislijsten;',
      'professioneel klantcontact en afstemming op locatie;',
      'herkennen van risico’s en hanteren van moeilijke items (banken, kasten, apparatuur, designmeubels);',
      'oplossen van kleine technische uitdagingen.',
    ],
    requirements: [
      'SAVAM / Inboedelverhuizer diploma of aantoonbare gelijkwaardige praktijkervaring;',
      'VCA Basis;',
      'verhuisliftcertificaat indien liften worden bediend;',
      'eigen volledige PBM en gereedschap.',
    ],
    rangeApplication: ['onderkant: standaard verhuisopdrachten;', 'bovenkant: complexere opdrachten of hogere zelfstandigheid.'],
  },
  {
    level: 'D',
    title: 'Export Packer',
    rate: '€ 30,00 – € 32,50 p/u',
    services: [
      'specialistisch exportverpakken (kunst, antiek, zee-/luchtvracht) conform ISPM15 en exportnormen;',
      'inspecteren van containers op schoonheid, lekkage en reukloosheid;',
      'afsluiten van containers met douanezegel in aanwezigheid van de klant;',
      'opmaken van gedetailleerde inventarislijsten voor export;',
      'houten kratten voorbereiden.',
    ],
    requirements: [
      'exportverpakker training of aantoonbare ervaring in exportverpakking;',
      'VCA Basis;',
      'eigen specialistisch gereedschap.',
    ],
    rangeApplication: [],
  },
  {
    level: 'E',
    title: 'Chauffeur–Verhuizer',
    rate: '€ 32,00 – € 35,00 p/u',
    services: [
      'rijden en manoeuvreren van verhuisvoertuigen (verhuiswagen/bus);',
      'laden en stuwen volgens norm;',
      'combineren van transport en verhuiswerk;',
      'naleving van wet- en regelgeving inzake rij- en rusttijden wegvervoer;',
      'inspecteren van verhuiswagen op schoonheid, lekkage en reukloosheid.',
    ],
    requirements: [
      'SAVAM Inboedelverhuizer;',
      'VCA Basis;',
      'rijbewijs B of C;',
      'Code 95 (indien van toepassing);',
      'eigen NIWO indien transport onder eigen naam plaatsvindt.',
    ],
    rangeApplication: [],
  },
  {
    level: 'F',
    title: 'Verhuisliftoperator',
    rate: '€ 35,00 – € 37,50 p/u',
    services: ['zelfstandig op- en afbouwen van verhuisliften;', 'veilig werken op hoogte;', 'bedienen van liftinstallaties.'],
    requirements: ['verhuisliftoperatorcertificaat;', 'VCA Basis;', 'veilig werken op hoogte;', 'eigen PBM.'],
    rangeApplication: [],
  },
  {
    level: 'G',
    title: 'Voorman / Teamcoördinator',
    rate: '€ 35,00 – € 38,50 p/u',
    services: [
      'coördinatie van werkzaamheden op locatie en leidinggeven aan een team (tot 5 man);',
      'afstemming tussen ingehuurde professionals;',
      'kwaliteitsbewaking en klantcommunicatie;',
      'toezicht op ladingzekering en schadepreventie;',
      'afhandeling van douaneformaliteiten (indien van toepassing, bijv. Zwitserland/Noorwegen);',
      'planning maken op locatie en teamdiscipline handhaven.',
    ],
    requirements: [
      'Voorman Inboedel- of Projectverhuizer diploma of aantoonbare leiderschapsvaardigheden;',
      'VCA VOL;',
      'rijbewijs C + Code 95 (indien van toepassing);',
      'eigen NIWO bij transport onder eigen verantwoordelijkheid.',
    ],
    rangeApplication: [],
  },
  {
    level: 'H',
    title: 'Handyman',
    rate: '€ 37,50 – € 40,00 p/u',
    services: [
      'uitvoeren van kleine kluswerkzaamheden gerelateerd aan verhuizingen (bijv. ophangen lampen, schilderijen);',
      'monteren van complexer meubilair;',
      'oplossen van kleine technische problemen.',
    ],
    includes: ['eigen bus / bedrijfsvoertuig;', 'eigen gereedschap.'],
    excludes: ['klein materiaal (pluggen, schroeven, kit e.d.) → op nacalculatie (gespecificeerd).'],
    requirements: ['Handyman-opleiding (Verhuiscollege of gelijkwaardig);', 'VCA Basis;', 'eigen PBM, bus en gereedschap.'],
    rangeApplication: [],
  },
];
