// This file is automatically generated. Do not modify it manually.
// To switch to a different Firebase project, use the 'UpdateFirebaseProjectTool' in the Studio.
export const firebaseConfig = {
  apiKey: process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain: "studio--gebr-stegeman-contracts.us-central1.hosted.app",
  projectId: "gebr-stegeman-contracts",
  storageBucket: "gebr-stegeman-contracts.appspot.com",
  messagingSenderId: "141566612300",
  appId: "1:141566612300:web:d6de8054acd93ad348f5e9",
  measurementId: process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};
