// This file is automatically generated. Do not modify it manually.
// To switch to a different Firebase project, use the 'UpdateFirebaseProjectTool' in the Studio.

const parsedFirebaseConfig =
  typeof process !== "undefined" && process.env.FIREBASE_WEBAPP_CONFIG
    ? JSON.parse(process.env.FIREBASE_WEBAPP_CONFIG)
    : undefined;

export const firebaseConfig = {
  apiKey:
    parsedFirebaseConfig?.apiKey ?? process.env.NEXT_PUBLIC_FIREBASE_API_KEY,
  authDomain:
    parsedFirebaseConfig?.authDomain ?? "gebr-stegeman-contracts.firebaseapp.com",
  projectId: parsedFirebaseConfig?.projectId ?? "gebr-stegeman-contracts",
  storageBucket:
    parsedFirebaseConfig?.storageBucket ?? "gebr-stegeman-contracts.appspot.com",
  messagingSenderId:
    parsedFirebaseConfig?.messagingSenderId ?? "141566612300",
  appId:
    parsedFirebaseConfig?.appId ??
    "1:141566612300:web:d6de8054acd93ad348f5e9",
  measurementId:
    parsedFirebaseConfig?.measurementId ??
    process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID,
};
